-- ================================================================
-- SatMonitor — Foreign Keys (Oracle)
--
-- Rodar DEPOIS de 02_tables.sql (todas as tabelas já criadas).
-- A exclusão em cascata é controlada pela aplicação (JPA orphanRemoval/
-- CascadeType.ALL), por isso as FKs não usam ON DELETE CASCADE —
-- o Hibernate apaga os filhos antes dos pais.
-- ================================================================

-- Missão → Agência (opcional)
ALTER TABLE TB_MISSAO ADD CONSTRAINT FK_MISSAO_AGENCIA
    FOREIGN KEY (agencia_id) REFERENCES TB_AGENCIA (id);

-- Missão → Operador dono
ALTER TABLE TB_MISSAO ADD CONSTRAINT FK_MISSAO_OPERADOR_DONO
    FOREIGN KEY (operador_dono_id) REFERENCES TB_OPERADOR (id);

-- Vínculo Operador x Missão
ALTER TABLE TB_OPERADOR_MISSAO ADD CONSTRAINT FK_OPMISSAO_OPERADOR
    FOREIGN KEY (operador_id) REFERENCES TB_OPERADOR (id);
ALTER TABLE TB_OPERADOR_MISSAO ADD CONSTRAINT FK_OPMISSAO_MISSAO
    FOREIGN KEY (missao_id) REFERENCES TB_MISSAO (id);

-- Satélite → Missão
ALTER TABLE TB_SATELITE ADD CONSTRAINT FK_SATELITE_MISSAO
    FOREIGN KEY (missao_id) REFERENCES TB_MISSAO (id);

-- Sensor → Satélite
ALTER TABLE TB_SENSOR ADD CONSTRAINT FK_SENSOR_SATELITE
    FOREIGN KEY (satelite_id) REFERENCES TB_SATELITE (id);

-- Subclasses do Sensor (herança JOINED): PK referencia a base
ALTER TABLE TB_SENSOR_TERMICO ADD CONSTRAINT FK_TERMICO_SENSOR
    FOREIGN KEY (id) REFERENCES TB_SENSOR (id);
ALTER TABLE TB_SENSOR_PRESSAO ADD CONSTRAINT FK_PRESSAO_SENSOR
    FOREIGN KEY (id) REFERENCES TB_SENSOR (id);
ALTER TABLE TB_SENSOR_RADIACAO ADD CONSTRAINT FK_RADIACAO_SENSOR
    FOREIGN KEY (id) REFERENCES TB_SENSOR (id);
ALTER TABLE TB_MAGNETOMETRO ADD CONSTRAINT FK_MAGNETOMETRO_SENSOR
    FOREIGN KEY (id) REFERENCES TB_SENSOR (id);

-- Leitura → Sensor
ALTER TABLE TB_LEITURA_SENSOR ADD CONSTRAINT FK_LEITURA_SENSOR
    FOREIGN KEY (sensor_id) REFERENCES TB_SENSOR (id);

-- Alerta → Leitura
ALTER TABLE TB_ALERTA ADD CONSTRAINT FK_ALERTA_LEITURA
    FOREIGN KEY (leitura_id) REFERENCES TB_LEITURA_SENSOR (id);
