-- ================================================================
-- SatMonitor — Teardown (Oracle)
--
-- Remove tudo na ordem inversa de dependência. Use para resetar o
-- schema antes de rodar 01→02→03 novamente.
-- CASCADE CONSTRAINTS derruba as FKs que apontam para a tabela.
-- ================================================================

DROP TABLE TB_LEITURA_SENSOR  CASCADE CONSTRAINTS;
DROP TABLE TB_SENSOR_TERMICO  CASCADE CONSTRAINTS;
DROP TABLE TB_SENSOR_PRESSAO  CASCADE CONSTRAINTS;
DROP TABLE TB_SENSOR_RADIACAO CASCADE CONSTRAINTS;
DROP TABLE TB_MAGNETOMETRO    CASCADE CONSTRAINTS;
DROP TABLE TB_SENSOR          CASCADE CONSTRAINTS;
DROP TABLE TB_SATELITE        CASCADE CONSTRAINTS;
DROP TABLE TB_OPERADOR_MISSAO CASCADE CONSTRAINTS;
DROP TABLE TB_MISSAO          CASCADE CONSTRAINTS;
DROP TABLE TB_OPERADOR        CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_OPERADOR;
DROP SEQUENCE SEQ_MISSAO;
DROP SEQUENCE SEQ_SATELITE;
DROP SEQUENCE SEQ_SENSOR;
DROP SEQUENCE SEQ_LEITURA;
